### ISSUE TITLE
Gulp task hangs (never completes) with last output "gulp-angular-protractor - Webdriver standalone server will be closed"

### ISSUE THREAD

**Issue by rhamilto** [rochejul/gulp-angular-protractor#33]
After updating gulp-angular-protractor to v0.2.0 so that tests would run under Chrome 54+, I am seeing an issue where the gulp-angular-protractor task never finishes.  The final output is "gulp-angular-protractor - Webdriver standalone server will be closed", but the task must be cancelled (command + c) in order to "complete" the task.

os:  macOS 10.12.2
java:  1.8.0_112
npm:  2.15.9
node:  v4.5.0

cc: @benjaminapetersen

**Comment by rochejul** [comment]
Hi

Have you tried to upgrade to v0.3.0 ? Because I have update the protractor version to deal some drivers issues

Regards

**Comment by rochejul** [comment]
Ping me if you still faced to this issue (if you could provide me an example or console logs, it will be great to help me to understand whats happened)

Regards

**Comment by rhamilto** [comment]
Thanks, @rochejul!  Unfortunately, upgrading to v0.3.0 did not resolve the issue (FWIW, I didn't notice v0.3.0 existed since [it lacks a git tag](https://github.com/rochejul/gulp-angular-protractor/releases)).

A copy of my log is available at https://gist.github.com/rhamilto/9ba008239aded9f4a765ffa282f3beba

**Comment by rochejul** [comment]
Hi

I have pushed the 0.3.0 tag (many thanks for your feedbakc)

I will have a look on your logs

Thanks

**Comment by mribichich** [comment]
Just in case, the new version of selenium standalone doesn't support the shutdown command via the url.

[SeleniumHQ/selenium#2958](https://github.com/SeleniumHQ/selenium/issues/2958)

**Comment by rochejul** [comment]
Many thanks

**Comment by rochejul** [comment]
Weird: I have test with 0.4.1, and it seems working, even when a test fails.

Cannot you provide a concret example please and give me as attachment ?

Many thanks

**Comment by rhamilto** [comment]
@rochejul, I upgraded to v0.4.1 and the problem persists with the tests.  See https://github.com/openshift/angular-key-value-editor/tree/master/test/e2e

Thanks.

**Comment by rochejul** [comment]
Could you run the examples (like example-02) and tell me if it terminates welly ?

Because I have test it on my windows and Ubuntu machines and it worked yesterday

Many thanks

**Comment by rhamilto** [comment]
example-02 did shut down, but not without an error ("protractor exited with code 1").

https://gist.github.com/rhamilto/87e5f0d94e984871ca35de5f8ad98276

**Comment by rochejul** [comment]
Here my output, based on the master branch (which contains updated examples to avoid a failure into an ssertion):
- https://gist.github.com/rochejul/028956e5ae3c6c4f7c0385951e14741d
- npm: 3.10.8
- node: 6.9.0
- git: 2.7.4.windows.1
- java: JRE 1.8.0_73-b02
- Windows 7 64bits

And when I have a failure assertion: https://gist.github.com/rochejul/c96c6b80056c7d90753a4a3b248f9cc7

I can found the  ("protractor exited with code 1"). I think this is due to this line: https://github.com/rochejul/gulp-angular-protractor/blob/master/gulp-angular-protractor/gulp-stream.js#L58

We launch protractor through a shell. So maybe as Eslint, if there is a "failure", we have an exit code to 1 (seehttps://github.com/eslint/eslint/issues/2949). So I think this is normal

I try to run your project on my local machine

Regards

**Comment by rochejul** [comment]
I think this is mot a problem of gulp tasks on your project:

````javascript
gulp.task('test-e2e', ['serve'], function(callback) {
    gulp
        .src(['example_spec.js'])
        .pipe(gulpProtractorAngular({
            configFile: test + 'protractor.conf.js',
            // baseUrl is needed for tests to navigate via relative paths
            args: ['--baseUrl', baseUrl],
            debug: false,
            autoStartStopServer: true
        }))
        .on('error', function(e) {
            console.log(e);
        })
        .on('end', callback);
});
````

In your gulp task, you run first with browserSync a local server and then run the tests. However, browserSync does not exit automatically

If you remove it:

````javascript
gulp.task('test-e2e', [], function(callback) {
    gulp
        .src(['example_spec.js'])
        .pipe(gulpProtractorAngular({
            configFile: test + 'protractor.conf.js',
            // baseUrl is needed for tests to navigate via relative paths
            args: ['--baseUrl', baseUrl],
            debug: false,
            autoStartStopServer: true
        }))
        .on('error', function(e) {
            console.log(e);
        })
        .on('end', callback);
});
````

The protractor server will be stopped. 

I think you need to call an exit method ( https://browsersync.io/docs/api#api-exit ?) when the tests are finished

Regards

**Comment by rhamilto** [comment]
Thanks for your help, @rochejul!
